# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc41a45ac11d418986a6ff76a43d9ad4"
name = "gil-test"
handle = "gil-test"
application_url = "https://nursery-reviewing-ruled-black.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gil-function-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://nursery-reviewing-ruled-black.trycloudflare.com/auth/callback",
  "https://nursery-reviewing-ruled-black.trycloudflare.com/auth/shopify/callback",
  "https://nursery-reviewing-ruled-black.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "unstable"

[pos]
embedded = false
